version: "3.8"

services:
  db:
    image: postgres:15
    container_name: order_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5433:5432"  # mude para evitar conflito com Postgres local
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "50051:50051"
      - "8081:8081"
    environment:
      DB_DSN: postgres://postgres:postgres@db:5432/orders?sslmode=disable

volumes:
  pgdata:
